name: gorbul
description: "GörBul Kayıp Eşya ve Yardımlaşma Uygulaması"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: any
  flutter_image_compress: any
  permission_handler: any
  intl: any
  path_provider: any
  firebase_core: any
  cloud_firestore: any
  firebase_storage: any
  firebase_auth: any
  geolocator: ^9.0.2
  http: any
  flutter_map: any
  latlong2: any
  url_launcher: any
  crypto: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/